### ISSUE TITLE
QQ file download error caught

### ISSUE THREAD

**Issue by SyperAI** [lmcsu/qq-neural-anime-tg#10]
QQ file download error caught (attempt #4): Client error '403 Forbidden' for url 'https://shadow-cv-activity4tlimit-1251316161.cos.ap-shanghai.myqcloud.com/folder7/activity/me_in_comics/share/d0a6eb3df7d1501ed8e77dc7296a16dd_8oyyc.jpg?sign=q-sign-algorithm%3Dsha1%26q-ak%3DAKIDmKchHz54FBtKUKDSO6atwjIzLRH0hOcZ%26q-sign-time%3D1696927483%3B1697273083%26q-key-time%3D1696927483%3B1697273083%26q-header-list%3Dhost%26q-url-param-list%3D%26q-signature%3Debc72ae670b762ec807b3d46090ca9896d2a995c'

Using proxy.  Tested them - all is ok

**Comment by lmcsu** [comment]
Make sure you're using the latest version of the sources and that you haven't broken anything.
If so, the problem is with your proxies.
Next time contact me by telegram if you don't want to wait several days for an answer, the link is in the README.
