### ISSUE TITLE
{"code":2119,"msg":"service upgrading"}

### ISSUE THREAD

**Issue by pkico** [lmcsu/qq-neural-anime-tg#11]
I use chinese proxy in config.ts, tried non-chinese  too. And always getting
Blocked {"code":2119,"msg":"service upgrading"}
QQ file upload error caught: Error: The Chinese website has blocked the bot, too bad 🤷‍♂️

Does the bot using proxy by default if I set in config.ts proxyUrl: ... ? I don't know what's the problem.
Please, help.

**Comment by lmcsu** [comment]
"service upgrading" read as "the service is not available in your area yet".
Try some another Chinese proxy. 
Not all of them work.
It's better to use proxy that exactly located at Beijing.

**Comment by pkico** [comment]
Thank you, could you tell what proxy do you use?

**Comment by lmcsu** [comment]
> Thank you, could you tell what proxy do you use?

uhhm... from Beijing
