### ISSUE TITLE
Error: Unable to upload the photo: Error: Try another photo.

### ISSUE THREAD

**Issue by 4mlsx** [lmcsu/qq-neural-anime-tg#6]
Some nasty error has occurred, please try again

Error: Unable to upload the photo: Error: Try another photo.

**Comment by lmcsu** [comment]
Some images couldn't pass the Chinese censorship.
If it asks you to try another photo, so in most cases you must try another photo.

**Comment by 4mlsx** [comment]
I'm getting error for all photo's

**Comment by lmcsu** [comment]
You may check your photos via my demo bot https://t.me/qq_neural_anime_bot

If it works, then just try to switch to another modes and countries.
